### ISSUE TITLE
how long does it take to train the model

### ISSUE THREAD

**Issue by kli017** [makeplanetoheaven/NlpModel#6]

**Comment by AlphaAvatar** [comment]
哪个模型

**Comment by kli017** [comment]
dfsmn的大约要跑多久

**Comment by AlphaAvatar** [comment]
2048-512，6层，bsz=8的时候，91W条数据大概4个半小时一次迭代，不过github上的是旧版本了，可能会慢一点，我明天会重新上传一个新的

**Comment by kli017** [comment]
好的期待更新! 91w条是4个数据集吗？我现在只跑了thchs30 loss到200左右感觉有点降不下去了。请问跑完最后WER大约多少呢？
